image: docker-registry.wikimedia.org/nodejs18-devel:latest

cache:
  paths:
    - node_modules/

install:
  stage: build
  script:
    - node --version
    - npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - node --version
    - npm run test
    - npm run lint
    - npx prettier . --list-different
  artifacts:
    paths:
      - node_modules

publishToTest:
  tags:
    - wmcs
  stage: deploy
  script:
    - node --version
    - npm run deployAll -- --apiUrl=https://test.wikidata.org/w/api.php
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  artifacts:
    paths:
      - node_modules
