name: Deploy to Test Wikidata
on:
  push:
    branches: [ main ]

jobs:
  deployToTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install

      - name: Deploy 🚀
        if: false # GitHub affected global Open Proxy block 😢
        env:
          BOT_USER: ${{ secrets.BOT_USER }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: yarn deployAll -- --apiUrl=https://test.wikidata.org/w/api.php
