name: Deploy to Test Wikidata
on:
  push:
    branches: [ main ]

jobs:
  deploToTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy 🚀
        run: yarn deployAll -- --apiUrl=https://test.wikidata.org/w/api.php
